#version: "3.9"

services:
  api: 
    image: ginapp
    #ports:
      #- 8090:8090
    expose:
      - "8090"
    networks:
      - api_network
    depends_on:
      - redis
    deploy: 
      replicas: 3

  redis:
    image: redis
    networks:
      - api_network
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - api_network

networks:
  api_network: {}
